[package]
name = "advent_of_code_2015"
version = "0.1.0"
authors = ["Galen Elias <gelias@gmail.com>"]

[dependencies]
clap = "*"
regex = "*"
itertools = "*"
md5 = "*"
permutohedron = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"

[[bin]]
name = "aoc"
path = "src/main.rs"